matrix:
  include:
    - os: linux
      dist: xenial
      language: go
      go:
        - "1.11.6"
      python: 2.7
      services:
        - mysql
      addons:
        apt:
          packages:
            - debhelper
            - devscripts
            - dh-systemd
            - fakeroot
            - libparse-debcontrol-perl
      env:
        - MYSQL_TEST_USER=travis
        - MYSQL_TEST_ADDR=127.0.0.1:3306
      before_install:
        - sudo pip install --upgrade pip virtualenv
        - virtualenv "${HOME}/FSENV"
        - mysql --print-defaults
        - mysql -u travis -e 'CREATE DATABASE db;'
        #- go get -u golang.org/x/lint/golint
      install:
        - source "${HOME}/FSENV/bin/activate" && pip install grpcio-tools && pip install -e .
        # TODO: remove 2 lines below when git.apache.org is back up or when
        # osquery-go uses a correct version of the Thrift library (the one
        # hosted on github.com and not on git.apache.org).
        - mkdir -p "$(go env GOPATH)/src/git.apache.org"
        - git clone https://github.com/apache/thrift.git "$(go env GOPATH)/src/git.apache.org/thrift.git"
        - go get -v -t ./... || true  # Install dependencies needed for tests.
      script:
        # We want to address all golint warnings, except for
        # https://github.com/golang/go/wiki/CodeReviewComments#doc-comments
        # - golint ./... | grep -v 'should have comment or be unexported'
        - go vet ./... || true
        - source "${HOME}/FSENV/bin/activate"
        - fleetspeak/build.sh && fleetspeak/test.sh
        # Install the built package and check that the fleetspeak-config program
        # doesn't error out.
        - cd fleetspeak
        - ./build-pkgs.sh
        - sudo ./test-package.sh ./fleetspeak-server_$(cat ../VERSION)_amd64.deb ./fleetspeak-client_$(cat ../VERSION)_amd64.deb

    # TODO: Find alternatives to Travis for MacOS testing.
    # Note that mysql is not available in OSX environments.
    #- os: osx
    #  language: go
    #  python: 2.7
    #  before_install:
    #    - git clone https://github.com/MacPython/terryfy
    #    # Install pip.
    #    - >-
    #      source terryfy/travis_tools.sh &&
    #      get_python_environment macpython 2.7.14
    #    - pip install --upgrade pip virtualenv
    #    - virtualenv "${HOME}/FSENV"
    #    - go version
    #  install:
    #    - source "${HOME}/FSENV/bin/activate" && pip install -e .
    #    - go get -v -t ./... # Install dependencies needed for tests.
    #  script:
    #    - source "${HOME}/FSENV/bin/activate"
    #    - fleetspeak/build.sh && fleetspeak/test.sh
